version: '3.7'
services:
    php:
        container_name: php
        build: ./
        ports:
          - "8001:8000"
        volumes:
          - ./:/var/www/app
        depends_on:
          - database
        entrypoint: symfony serve --no-tls --port=8000 --allow-http
    database:
        container_name: db
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3307:3306"

volumes:
  db-data:
