version: '3.7'
services:
    php8-sf6:
        container_name: app
        build: ./
        ports:
            - "8000:8000"
        volumes:
            - ./project:/var/www/html

    database:
        container_name: db
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: db
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432"

volumes:
  db-data: