version: '3.7'
services:
    php8-sf6:
        container_name: app
        build: ./
        ports:
            - "8000:8000"
        volumes:
            - ./project:/var/www/html

    database:
        container_name: db
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3307:3306"

volumes:
  db-data: